import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import '@/app/styles/global.css';
import '@/app/styles/stars.scss';
import '@/app/styles/app.scss';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <title>Storytime</title>
      </head>
      <body
        suppressHydrationWarning={true}
        className={
          inter.className +
          ' flex min-h-screen flex-col items-center justify-between p-24'
        }
      >
        <header className="w-full max-w-5xl items-center justify-between font-mono text-sm lg:flex"></header>
        <main className="background">
          <div className="cluster1"></div>
          <div className="cluster2"></div>
          <div className="cluster3"></div>
          <div className="stars1"></div>
          <div className="stars2"></div>
          <div className="stars3"></div>
          <div className="content">{children}</div>
        </main>
      </body>
    </html>
  );
}
