import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import './styles.scss';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <title>Storytime</title>
      </head>
      <body
        className={
          inter.className +
          ' flex min-h-screen flex-col items-center justify-between p-24'
        }
      >
        <header className="w-full max-w-5xl items-center justify-between font-mono text-sm lg:flex"></header>
        <main className="background">
          <div id="stars"></div>
          <div id="stars2"></div>
          <div id="stars3"></div>
          <div id="title">
            {children}
            <br />
          </div>
        </main>
      </body>
    </html>
  );
}
